import { insertHorizontalRule, insertTable, setCodeLanguageResult, toggleBlockquote, toggleCodeFence, toggleHeading, toggleList, toggleParagraph, toggleTaskDone } from "./blocks.js";
import { deleteSelectionResult, markdownShortcut, smartBackspace, smartDelete, smartOutdent } from "./editing.js";
import { insertImage, insertLink, wrapCode, wrapInline } from "./inline.js";
import { tableColumnResult, tableDeleteRowResult, tablePositionForOffset, tableRowInsertionResult } from "./tables.js";
import { normalizeLineEndings } from "../core/text.js";
import { fail, insertionTransaction, okNoop } from "../core/transactions.js";

export function installBuiltInActions(api) {
    const r = a => api.registerAction(a);
    r({ id: "editor.insertText", label: "Insert text", group: "Editor", structural: false, run: (ctx, args = {}) => insertionTransaction(ctx, "editor.insertText", normalizeLineEndings(args.text ?? ""), normalizeLineEndings(args.text ?? "").length, "insertText") });
    r({ id: "editor.replaceSelection", label: "Replace selection", group: "Editor", structural: false, run: (ctx, args = {}) => insertionTransaction(ctx, "editor.replaceSelection", normalizeLineEndings(args.text ?? ""), normalizeLineEndings(args.text ?? "").length, "replaceSelection") });
    r({ id: "editor.insertParagraph", label: "Insert paragraph", group: "Editor", defaultShortcut: "Enter", run: ctx => insertionTransaction(ctx, "editor.insertParagraph", "\n", 1, "insertParagraph") });
    r({ id: "editor.insertSoftBreak", label: "Insert soft break", group: "Editor", defaultShortcut: "Shift+Enter", run: ctx => insertionTransaction(ctx, "editor.insertSoftBreak", "  \n", 3, "insertSoftBreak") });
    r({ id: "editor.smartEnter", label: "Smart enter", group: "Editor", defaultShortcut: "Enter", run: ctx => api.smartEnter(ctx) });
    r({ id: "editor.smartTab", label: "Indent", group: "Editor", defaultShortcut: "Tab", run: ctx => api.smartTab(ctx) });
    r({ id: "editor.smartOutdent", label: "Outdent", group: "Editor", defaultShortcut: "Shift+Tab", run: ctx => smartOutdent(ctx) });
    r({ id: "editor.smartBackspace", label: "Smart backspace", group: "Editor", defaultShortcut: "Backspace", run: ctx => smartBackspace(ctx) });
    r({ id: "editor.smartDelete", label: "Smart delete", group: "Editor", defaultShortcut: "Delete", run: ctx => smartDelete(ctx) });
    r({ id: "editor.markdownShortcut", label: "Markdown shortcut", group: "Editor", defaultShortcut: "Space", run: ctx => markdownShortcut(ctx) });
    r({ id: "editor.deleteSelection", label: "Delete selection", group: "Editor", run: ctx => deleteSelectionResult(ctx, "editor.deleteSelection") });
    r({ id: "editor.selectAllExpand", label: "Expand selection", group: "Editor", defaultShortcut: "Mod+A", viewSafe: true, readonlySafe: true, run: () => { api.expandSelection(); return okNoop("Selection expanded."); } });
    r({ id: "history.undo", label: "Undo", group: "History", defaultShortcut: "Mod+Z", run: (_ctx, _args, options) => api.undo({ source: options?.source || "api" }) ? { ...okNoop("Undo."), actionHandled: true } : fail("not-applicable") });
    r({ id: "history.redo", label: "Redo", group: "History", defaultShortcut: "Mod+Shift+Z", run: (_ctx, _args, options) => api.redo({ source: options?.source || "api" }) ? { ...okNoop("Redo."), actionHandled: true } : fail("not-applicable") });
    r({ id: "block.paragraph", label: "Paragraph", description: "Convert current block to paragraph", group: "Blocks", aliases: ["p", "text", "clear"], visibleInSlash: true, run: ctx => toggleParagraph(ctx) });
    for (let level = 1; level <= 6; level += 1) r({ id: `block.heading.${level}`, label: `Heading ${level}`, description: `Convert to heading level ${level}`, group: "Blocks", aliases: [`h${level}`, `heading${level}`], keywords: ["title", "section"], defaultShortcut: level <= 3 ? `Mod+Alt+${level}` : undefined, visibleInSlash: true, run: ctx => toggleHeading(ctx, level) });
    r({ id: "block.bulletList", label: "Bullet list", description: "Create an unordered list", group: "Blocks", aliases: ["bullet", "ul", "list"], visibleInSlash: true, run: ctx => toggleList(ctx, "bullet") });
    r({ id: "block.orderedList", label: "Numbered list", description: "Create an ordered list", group: "Blocks", aliases: ["number", "numbered", "ol"], visibleInSlash: true, run: ctx => toggleList(ctx, "ordered") });
    r({ id: "block.taskList", label: "Task list", description: "Create a task list", group: "Blocks", aliases: ["todo", "task", "checkbox"], visibleInSlash: true, run: ctx => toggleList(ctx, "task") });
    r({ id: "block.taskDone", label: "Toggle task done", description: "Toggle task checkbox state", group: "Blocks", aliases: ["done", "check"], visibleInSlash: true, run: ctx => toggleTaskDone(ctx) });
    r({ id: "block.blockquote", label: "Blockquote", description: "Create a blockquote", group: "Blocks", aliases: ["quote", "blockquote"], visibleInSlash: true, run: ctx => toggleBlockquote(ctx) });
    r({ id: "block.codeFence", label: "Code block", description: "Create a fenced code block", group: "Insert", aliases: ["code", "pre", "fence"], visibleInSlash: true, run: (ctx, args) => toggleCodeFence(ctx, args) });
    r({ id: "block.horizontalRule", label: "Horizontal rule", description: "Insert horizontal rule", group: "Insert", aliases: ["hr", "divider", "rule"], visibleInSlash: true, run: ctx => insertHorizontalRule(ctx) });
    r({ id: "block.table", label: "Table", description: "Insert a markdown table", group: "Insert", aliases: ["table", "grid"], visibleInSlash: true, run: (ctx, args = {}) => insertTable(ctx, args) });
    r({ id: "table.insertRowAfter", label: "Insert table row", group: "Table", run: ctx => { const block = api.findBlockAtOffset(ctx.selectionStart, "table"); return block ? tableRowInsertionResult(ctx, block, ctx.currentLine, "after-row") : fail("not-applicable"); } });
    r({ id: "table.insertColumnAfter", label: "Insert table column", group: "Table", run: ctx => { const block = api.findBlockAtOffset(ctx.selectionStart, "table"); const pos = block ? tablePositionForOffset(block, ctx.selectionStart) : null; return block ? tableColumnResult(ctx, block, pos?.col ?? 0, "insert-after") : fail("not-applicable"); } });
    r({ id: "table.deleteRow", label: "Delete table row", group: "Table", run: ctx => { const block = api.findBlockAtOffset(ctx.selectionStart, "table"); const pos = block ? tablePositionForOffset(block, ctx.selectionStart) : null; return block ? tableDeleteRowResult(ctx, block, pos?.row >= 0 ? pos.row : 0) : fail("not-applicable"); } });
    r({ id: "table.deleteColumn", label: "Delete table column", group: "Table", run: ctx => { const block = api.findBlockAtOffset(ctx.selectionStart, "table"); const pos = block ? tablePositionForOffset(block, ctx.selectionStart) : null; return block ? tableColumnResult(ctx, block, pos?.col ?? 0, "delete") : fail("not-applicable"); } });
    r({ id: "code.setLanguage", label: "Set code language", group: "Code", run: (ctx, args = {}) => { const block = api.findBlockAtOffset(ctx.selectionStart, "code-fence"); return block ? setCodeLanguageResult(ctx, block, String(args.language ?? "")) : fail("not-applicable"); } });
    r({ id: "inline.bold", label: "Bold", description: "Strong emphasis", group: "Inline", aliases: ["bold", "strong"], defaultShortcut: "Mod+B", visibleInSlash: true, run: ctx => wrapInline(ctx, "**", "**", "Bold") });
    r({ id: "inline.italic", label: "Italic", description: "Emphasis", group: "Inline", aliases: ["italic", "em"], defaultShortcut: "Mod+I", visibleInSlash: true, run: ctx => wrapInline(ctx, "*", "*", "Italic") });
    r({ id: "inline.code", label: "Inline code", description: "Inline code span", group: "Inline", aliases: ["inline-code", "codespan"], defaultShortcut: "Mod+E", visibleInSlash: true, run: ctx => wrapCode(ctx) });
    r({ id: "inline.strikethrough", label: "Strikethrough", description: "Strikethrough text", group: "Inline", aliases: ["strike", "s"], defaultShortcut: "Mod+Shift+X", visibleInSlash: true, run: ctx => wrapInline(ctx, "~~", "~~", "Strikethrough") });
    r({ id: "inline.link", label: "Link", description: "Insert or wrap a link", group: "Inline", aliases: ["link", "url"], defaultShortcut: "Mod+K", visibleInSlash: true, run: (ctx, args = {}) => insertLink(ctx, args) });
    r({ id: "inline.image", label: "Image", description: "Insert an image", group: "Inline", aliases: ["image", "img", "picture"], visibleInSlash: true, run: (ctx, args = {}) => insertImage(ctx, args) });
    r({ id: "view.live", label: "Live mode", group: "View", viewSafe: true, readonlySafe: true, run: () => { api.setMode("live"); return okNoop("Live mode."); } });
    r({ id: "view.source", label: "Source mode", group: "View", viewSafe: true, readonlySafe: true, run: () => { api.setMode("source"); return okNoop("Source mode."); } });
    r({ id: "completion.close", label: "Close completion", group: "Completion", viewSafe: true, run: () => { api.closeCompletion(); return okNoop("Completion closed."); } });
    r({ id: "completion.next", label: "Next completion", group: "Completion", viewSafe: true, run: () => { api.moveCompletion(1); return okNoop(); } });
    r({ id: "completion.previous", label: "Previous completion", group: "Completion", viewSafe: true, run: () => { api.moveCompletion(-1); return okNoop(); } });
    r({ id: "completion.first", label: "First completion", group: "Completion", viewSafe: true, run: () => { api.setCompletionIndex(0, 1); return okNoop(); } });
    r({ id: "completion.last", label: "Last completion", group: "Completion", viewSafe: true, run: () => { api.setCompletionIndex(api.completionCount() - 1, -1); return okNoop(); } });
    r({ id: "completion.accept", label: "Accept completion", group: "Completion", viewSafe: true, run: () => api.acceptCompletion("action") });
  }
