#!/usr/bin/env node
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = resolve(root, "src/writemark-editor.js");
const distDir = resolve(root, "dist");
const modulePath = resolve(distDir, "writemark-editor.js");
const globalPath = resolve(distDir, "writemark-editor.global.js");
const legacyPath = resolve(distDir, "md-live-editor.js");
const checkOnly = process.argv.includes("--check");

const source = await readFile(sourcePath, "utf8");
const exportStatement = "export { WritemarkEditorElement, MdLiveEditorElement, renderMarkdown, renderInlineMarkdown, parseBlocks, parseListItem, parseHeading, parseBlockquote, parseFixtureMarkedValue, serializeMarkedValue, htmlToMarkdown, tsvToMarkdownTable };";
const globalStatement = `globalThis.WritemarkEditor = Object.freeze({
  WritemarkEditorElement,
  MdLiveEditorElement,
  renderMarkdown,
  renderInlineMarkdown,
  parseBlocks,
  parseListItem,
  parseHeading,
  parseBlockquote,
  parseFixtureMarkedValue,
  serializeMarkedValue,
  htmlToMarkdown,
  tsvToMarkdownTable
});`;

if (!source.includes(exportStatement)) {
  throw new Error("Could not find the expected Writemark ESM export statement.");
}

const classicBody = source.replace(exportStatement, globalStatement);
const globalOutput = `/*
 * Generated from src/writemark-editor.js by scripts/build.mjs.
 * Do not edit this file directly.
 */
(() => {
${classicBody}
})();
`;
const legacyOutput = 'export * from "./writemark-editor.js";\n';

if (checkOnly) {
  const expected = [
    [modulePath, source],
    [globalPath, globalOutput],
    [legacyPath, legacyOutput],
  ];
  for (const [file, contents] of expected) {
    let existing = "";
    try {
      existing = await readFile(file, "utf8");
    } catch {
      throw new Error(`${file} does not exist. Run npm run build.`);
    }
    if (existing !== contents) {
      throw new Error(`${file} is stale. Run npm run build.`);
    }
  }
} else {
  await mkdir(distDir, { recursive: true });
  await writeFile(modulePath, source);
  await writeFile(globalPath, globalOutput);
  await writeFile(legacyPath, legacyOutput);
}
