#!/usr/bin/env node
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = resolve(root, "writemark-editor.js");
const outputPath = resolve(root, "writemark-editor.global.js");
const checkOnly = process.argv.includes("--check");

const source = await readFile(sourcePath, "utf8");
const exportStatement = "export { WritemarkEditorElement, MdLiveEditorElement, renderMarkdown, renderInlineMarkdown, parseBlocks, parseListItem, parseHeading, parseBlockquote, parseFixtureMarkedValue, serializeMarkedValue, htmlToMarkdown, tsvToMarkdownTable };";
const globalStatement = `globalThis.WritemarkEditor = Object.freeze({
  WritemarkEditorElement,
  MdLiveEditorElement,
  renderMarkdown,
  renderInlineMarkdown,
  parseBlocks,
  parseListItem,
  parseHeading,
  parseBlockquote,
  parseFixtureMarkedValue,
  serializeMarkedValue,
  htmlToMarkdown,
  tsvToMarkdownTable
});`;

if (!source.includes(exportStatement)) {
  throw new Error("Could not find the expected Writemark ESM export statement.");
}

const classicBody = source.replace(exportStatement, globalStatement);
const output = `/*
 * Generated from writemark-editor.js by scripts/build-global.mjs.
 * Do not edit this file directly.
 */
(() => {
${classicBody}
})();
`;

if (checkOnly) {
  let existing = "";
  try {
    existing = await readFile(outputPath, "utf8");
  } catch {
    throw new Error("writemark-editor.global.js does not exist. Run npm run build.");
  }
  if (existing !== output) {
    throw new Error("writemark-editor.global.js is stale. Run npm run build.");
  }
} else {
  await writeFile(outputPath, output);
}
